import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { register } from '../services/authApi';
import { saveSession } from '../services/session';
import { AuthLayout, ErrorMessage, Field } from './LoginPage';

const config = { donor: { label: 'Donor', role: 'DONOR', headline: 'Give Life. Register as a Donor.', description: 'Join a community of everyday heroes.', fields: ['Blood group', 'City / region'] }, hospital: { label: 'Hospital', role: 'HOSPITAL', headline: 'Partner With VitalFlow', description: 'Register your facility to manage critical blood requests.', fields: ['Hospital name', 'Registration number', 'City / region'] }, 'blood-bank': { label: 'Blood Bank', role: 'BLOOD_BANK', headline: 'Scale Your Impact', description: 'Join the network and manage inventory with precision.', fields: ['Facility name', 'Registration number', 'City / region'] } };
export default function RegistrationPage() { const { role = 'donor' } = useParams(); const selected = config[role] || config.donor; const navigate = useNavigate(); const [form, setForm] = useState({ fullName: '', email: '', phoneNumber: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const update = key => e => setForm({ ...form, [key]: e.target.value }); const submit = async e => { e.preventDefault(); setError(''); setLoading(true); try { const data = await register({ ...form, role: selected.role }); saveSession(data); navigate('/registration-success', { state: { role: selected.label } }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <AuthLayout title={selected.headline} subtitle={selected.description}><div className="mb-7 rounded-lg bg-blue-50 p-4 text-sm text-slate-600">Create your account first. Your detailed {selected.label.toLowerCase()} profile can be completed from the dashboard.</div><form onSubmit={submit} className="space-y-5"><Field label="Full name"><input className="input" value={form.fullName} onChange={update('fullName')} required placeholder="Your full name" /></Field><div className="grid gap-5 md:grid-cols-2"><Field label="Email"><input className="input" type="email" value={form.email} onChange={update('email')} placeholder="you@example.com" /></Field><Field label="Phone number"><input className="input" value={form.phoneNumber} onChange={update('phoneNumber')} placeholder="+1 555 000 0000" /></Field></div><Field label="Password"><input className="input" type="password" minLength="8" value={form.password} onChange={update('password')} required placeholder="At least 8 characters" /></Field>{error && <ErrorMessage>{error}</ErrorMessage>}<button className="primary-button w-full" disabled={loading}>{loading ? 'Creating account...' : `Complete ${selected.label} Registration`}</button><p className="text-center text-sm text-slate-500">Already registered? <Link to="/login" className="font-semibold text-primary">Login here</Link></p></form></AuthLayout>;
}
