import { BrowserRouter, Routes, Route, Navigate, Link } from 'react-router-dom';
import './index.css';

const roles = ['Donor', 'Hospital', 'Blood Bank'];
function Shell({ children }) { return <div className="min-h-screen"><header className="h-20 bg-white border-b flex items-center justify-between px-6 md:px-12"><Link to="/" className="text-2xl font-bold text-primary">💧 VitalFlow</Link><nav className="hidden md:flex gap-6 text-sm text-slate-600"><a href="#donors">Donors</a><a href="#hospitals">Hospitals/Recipients</a><a href="#about">About Us</a></nav><Link to="/login" className="rounded-lg bg-primary px-5 py-2 text-white">Login</Link></header>{children}</div> }
function Landing() { return <Shell><main><section className="bg-blue-50 px-6 py-24 text-center"><p className="mb-5 inline-block rounded-full bg-white px-4 py-2 text-sm text-primary">● Emergency Need: O Negative</p><h1 className="mx-auto max-w-3xl text-4xl font-bold md:text-6xl">Connecting Life, One Drop at a Time</h1><p className="mx-auto mt-6 max-w-2xl text-lg text-slate-600">A simple blood management system connecting donors directly with hospitals and blood banks.</p></section><section className="grid md:grid-cols-3">{roles.map((role, i) => <div key={role} className={`p-10 text-center ${i === 1 ? 'bg-navy text-white' : 'bg-white'}`}><h2 className="text-3xl font-bold">{role === 'Donor' ? 'Become a Lifesaver' : role === 'Hospital' ? 'Streamline Your Supply' : 'Scale Your Impact'}</h2><p className="my-6">Register and use VitalFlow tools designed for your role.</p><Link to={`/register/${role.toLowerCase().replace(' ', '-')}`} className="inline-block rounded-lg bg-primary px-6 py-3 text-white">Register as {role}</Link></div>)}</section></main></Shell> }
function Login() { return <AuthForm title="Welcome back" button="Login" /> }
function Register({ role }) { return <AuthForm title={`Register as ${role}`} button="Create Account" role={role.toUpperCase().replace(' ', '_')} /> }
function AuthForm({ title, button, role }) { return <Shell><main className="mx-auto max-w-xl px-6 py-16"><div className="rounded-xl border bg-white p-8 shadow-sm"><h1 className="text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-600">Create your account to join the VitalFlow network.</p><form className="mt-8 space-y-5"><label className="block text-sm font-semibold">Full name<input className="mt-2 w-full rounded-lg border p-3" required /></label><label className="block text-sm font-semibold">Email or phone<input className="mt-2 w-full rounded-lg border p-3" required /></label><label className="block text-sm font-semibold">Password<input type="password" className="mt-2 w-full rounded-lg border p-3" required /></label>{role && <label className="block text-sm font-semibold">Role<select defaultValue={role} className="mt-2 w-full rounded-lg border p-3"><option value="DONOR">Donor</option><option value="HOSPITAL">Hospital</option><option value="BLOOD_BANK">Blood Bank</option></select></label>}<button className="w-full rounded-lg bg-primary py-3 font-semibold text-white">{button}</button></form></div></main></Shell> }
function Dashboard({ role }) { return <Shell><main className="p-6 md:p-12"><h1 className="text-4xl font-bold">{role} Dashboard</h1><p className="mt-2 text-slate-600">Your VitalFlow workspace is ready.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{['Overview','Profile','Requests'].map(item => <div className="rounded-xl border bg-white p-6 shadow-sm" key={item}><h2 className="text-xl font-semibold">{item}</h2><p className="mt-2 text-slate-500">This section will be completed in the {role} module.</p></div>)}</div></main></Shell> }
export default function App() { return <Routes><Route path="/" element={<Landing />} /><Route path="/login" element={<Login />} /><Route path="/register/donor" element={<Register role="Donor" />} /><Route path="/register/hospital" element={<Register role="Hospital" />} /><Route path="/register/blood-bank" element={<Register role="Blood Bank" />} /><Route path="/donor/dashboard" element={<Dashboard role="Donor" />} /><Route path="/hospital/dashboard" element={<Dashboard role="Hospital" />} /><Route path="/blood-bank/dashboard" element={<Dashboard role="Blood Bank" />} /><Route path="*" element={<Navigate to="/" />} /></Routes> }
